### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by lvl99** [segmentio/localstorage-retry#14]
Attempting to run some tests with jest (CRA) and I get the following error:

```
Test suite failed to run

    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/@segment/localstorage-retry/lib/schedule.js:12:9)
      at Object.<anonymous> (node_modules/@segment/localstorage-retry/lib/index.js:6:16)
```

When looking at the code for [`lib/schedule.js`](https://github.com/segmentio/localstorage-retry/blob/0632fb943fc111b6dbf8f36bff5abc6568ffc65e/lib/schedule.js#L7-L12) it references `window.setTimeout`, `window.clearTimeout` and `window.Date`. I think this can conflict with jest's mocking of the `window` object and timer functions.

**Comment by f2prateek** [comment]
Hi! Sorry for the delay. Our tests in this repo are passing as far as I can tell (https://circleci.com/gh/segmentio/localstorage-retry). Can you clarify what your setup looks like so we can reproduce this ourselves?

**Comment by f2prateek** [comment]
(sorry accidentiallly hit the close button)

**Comment by lvl99** [comment]
Thanks for the response @f2prateek. I am using Jest with Create React App. I'm also mocking localstorage with (jest-localstorage-mock)[https://github.com/clarkbw/jest-localstorage-mock]

**Comment by lvl99** [comment]
I managed to reproduce this issue in a basic CRA repo: https://github.com/lvl99/localstorage-retry-cra-jest-test.

You can view the issue by running `yarn test` from the CLI.

**Comment by f2prateek** [comment]
cool - feel free to post back here if you have an update :)
