### ISSUE TITLE
disappeared from npm?

### ISSUE THREAD

**Issue by cthorner** [segmentio/localstorage-retry#4]
I'm seeing the cached version(via google cache):

https://webcache.googleusercontent.com/search?q=cache:ERM8uEsWBecJ:https://www.npmjs.com/package/%40segment/localstorage-retry+&cd=1&hl=en&ct=clnk&gl=us

but the live version is returning 404:

https://www.npmjs.com/package/@segment/localstorage-retry

NPM status is reporting all services are up and other @segment packages are available.

**Comment by stephenmathieson** [comment]
@sperand-io @tsholmes any idea what happened here? (pinging you since you're recent contributors)

**Comment by tsholmes** [comment]
@cthorner sorry about that. looks like it got accidentally changed to private on a recent publish. I switched the access back to public.
